// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5NvZ9w14LhN4St-5PZr0JTiYH4xzAiW8',
    appId: '1:362273332669:android:db28f819b87e83a36386d4',
    messagingSenderId: '362273332669',
    projectId: 'navedh-7cfde',
    storageBucket: 'navedh-7cfde.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUvhyBrvc4kdVnQT-WiJotmvH3GQaQc68',
    appId: '1:362273332669:ios:5a6e6233379105546386d4',
    messagingSenderId: '362273332669',
    projectId: 'navedh-7cfde',
    storageBucket: 'navedh-7cfde.appspot.com',
    androidClientId: '362273332669-jcl2b3ndejm32ojnv7h4ak6mhl2871mf.apps.googleusercontent.com',
    iosClientId: '362273332669-6fgonr7c9l6i08k0aqduhs37cj7joibs.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );

}